# Broker MQTT. Rodar na pasta do projeto:
#   mosquitto -c mosquitto.conf -v
allow_anonymous true

# sem TLS
listener 1884

# com TLS (mesmos certificados do orquestrador)
listener 8883
cafile certificados/ca.crt
certfile certificados/servidor.crt
keyfile certificados/servidor.key
tls_version tlsv1.3
